"use client";

import React, { useState, useEffect, useCallback, useRef } from "react";
import Link from "next/link";
import { ProtectedRoute } from "@/lib/protected-route";
import { useAuth } from "@/lib/auth-context";
import PatientSidebar from "@/components/patient-sidebar";
import { appointmentService } from "@/lib/api-services";
import {
  Calendar, Clock, Stethoscope, Plus, RefreshCw, AlertCircle,
  CheckCircle2, XCircle, RotateCcw, Ban, ChevronRight, Info,
  Phone, Download, FileText, Loader2, Bell, ArrowRight
} from "lucide-react";

const STATUS_CONFIG: Record<string, { label: string; color: string; bg: string; border: string; icon: React.ReactNode }> = {
  pending: {
    label: "Pending Confirmation",
    color: "text-amber-700 dark:text-amber-400",
    bg: "bg-amber-50 dark:bg-amber-900/20",
    border: "border-amber-200 dark:border-amber-700",
    icon: <Clock className="w-3.5 h-3.5" />,
  },
  confirmed: {
    label: "Confirmed",
    color: "text-emerald-700 dark:text-emerald-400",
    bg: "bg-emerald-50 dark:bg-emerald-900/20",
    border: "border-emerald-200 dark:border-emerald-700",
    icon: <CheckCircle2 className="w-3.5 h-3.5" />,
  },
  rejected: {
    label: "Rejected",
    color: "text-red-700 dark:text-red-400",
    bg: "bg-red-50 dark:bg-red-900/20",
    border: "border-red-200 dark:border-red-700",
    icon: <XCircle className="w-3.5 h-3.5" />,
  },
  rescheduled: {
    label: "Rescheduled",
    color: "text-blue-700 dark:text-blue-400",
    bg: "bg-blue-50 dark:bg-blue-900/20",
    border: "border-blue-200 dark:border-blue-700",
    icon: <RotateCcw className="w-3.5 h-3.5" />,
  },
  cancelled: {
    label: "Cancelled",
    color: "text-slate-600 dark:text-slate-400",
    bg: "bg-slate-100 dark:bg-slate-800",
    border: "border-slate-200 dark:border-slate-700",
    icon: <Ban className="w-3.5 h-3.5" />,
  },
  completed: {
    label: "Completed",
    color: "text-purple-700 dark:text-purple-400",
    bg: "bg-purple-50 dark:bg-purple-900/20",
    border: "border-purple-200 dark:border-purple-700",
    icon: <CheckCircle2 className="w-3.5 h-3.5" />,
  },
};

function StatusBadge({ status }: { status: string }) {
  const cfg = STATUS_CONFIG[status] || STATUS_CONFIG.pending;
  return (
    <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold border ${cfg.color} ${cfg.bg} ${cfg.border}`}>
      {cfg.icon}
      {cfg.label}
    </span>
  );
}

function AppointmentSkeleton() {
  return (
    <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 shadow-sm animate-pulse">
      <div className="flex justify-between items-start">
        <div className="flex gap-4">
          <div className="w-12 h-12 rounded-2xl bg-slate-200 dark:bg-slate-700" />
          <div className="space-y-2">
            <div className="h-4 w-48 bg-slate-200 dark:bg-slate-700 rounded" />
            <div className="h-3 w-32 bg-slate-100 dark:bg-slate-800 rounded" />
            <div className="h-3 w-56 bg-slate-100 dark:bg-slate-800 rounded" />
          </div>
        </div>
        <div className="h-7 w-28 bg-slate-200 dark:bg-slate-700 rounded-full" />
      </div>
    </div>
  );
}

function AppointmentCard({
  apt,
  onCancel,
  cancelling,
}: {
  apt: any;
  onCancel: (id: string) => void;
  cancelling: boolean;
}) {
  const [showChecklist, setShowChecklist] = useState(false);

  const effectiveDate = apt.status === "rescheduled" && apt.rescheduled_date
    ? apt.rescheduled_date
    : apt.appointment_date;
  const effectiveTime = apt.status === "rescheduled" && apt.rescheduled_time
    ? apt.rescheduled_time
    : apt.appointment_time;

  const isUpcoming = ["pending", "confirmed", "rescheduled"].includes(apt.status);

  const handleDownloadSlip = () => {
    const content = `
MEDIPILOT AI — APPOINTMENT SLIP
================================
Appointment ID : ${apt.appointment_id}
Doctor         : ${apt.doctor_name}
Department     : ${apt.department}
Date           : ${effectiveDate}
Time           : ${effectiveTime}
Type           : ${apt.consultation_type}
Status         : ${apt.status.toUpperCase()}
Reason         : ${apt.reason || "General Consultation"}
================================
Generated by MediPilot AI Patient Portal
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Appointment_Slip_${apt.appointment_id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className={`bg-white dark:bg-slate-900 border rounded-2xl p-5 shadow-sm space-y-4 transition-all hover:shadow-md ${
      apt.status === "pending" ? "border-amber-200 dark:border-amber-800/50" :
      apt.status === "confirmed" ? "border-emerald-200 dark:border-emerald-800/50" :
      "border-slate-200 dark:border-slate-800"
    }`}>
      {/* Header Row */}
      <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-3">
        <div className="flex items-start gap-4">
          {/* Doctor Avatar */}
          <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-emerald-400 to-teal-500 flex items-center justify-center shrink-0 shadow-sm">
            <span className="text-white font-bold text-sm">
              {apt.doctor_name.split(" ").map((n: string) => n[0]).join("").substring(0, 2).toUpperCase()}
            </span>
          </div>

          <div>
            <div className="flex items-center gap-2 flex-wrap">
              <h3 className="font-bold text-slate-900 dark:text-white text-sm">{apt.doctor_name}</h3>
              <span className="text-xs font-medium text-slate-500 bg-slate-100 dark:bg-slate-800 px-2 py-0.5 rounded-md">
                {apt.department}
              </span>
            </div>
            <div className="flex flex-wrap items-center gap-3 mt-1.5 text-xs text-slate-500">
              <span className="flex items-center gap-1">
                <Calendar className="w-3.5 h-3.5 text-emerald-500" />
                {effectiveDate}
                {apt.status === "rescheduled" && apt.rescheduled_date && (
                  <span className="text-blue-500 font-semibold ml-1">(rescheduled)</span>
                )}
              </span>
              <span className="flex items-center gap-1">
                <Clock className="w-3.5 h-3.5 text-purple-500" />
                {effectiveTime}
              </span>
              <span className="flex items-center gap-1">
                <Stethoscope className="w-3.5 h-3.5 text-slate-400" />
                {apt.consultation_type}
              </span>
            </div>
            {apt.reason && (
              <p className="text-xs text-slate-400 mt-1 italic">"{apt.reason}"</p>
            )}
          </div>
        </div>

        <StatusBadge status={apt.status} />
      </div>

      {/* Rescheduled Info */}
      {apt.status === "rescheduled" && apt.rescheduled_date && (
        <div className="flex items-start gap-2 p-3 bg-blue-50 dark:bg-blue-900/20 rounded-xl border border-blue-100 dark:border-blue-800/50 text-xs text-blue-700 dark:text-blue-300">
          <Info className="w-3.5 h-3.5 shrink-0 mt-0.5" />
          <span>
            <strong>Rescheduled by Doctor:</strong> New slot is {apt.rescheduled_date} at {apt.rescheduled_time}.
            Original slot was {apt.appointment_date} at {apt.appointment_time}.
          </span>
        </div>
      )}

      {/* Rejected Info */}
      {apt.status === "rejected" && (
        <div className="flex items-start gap-2 p-3 bg-red-50 dark:bg-red-900/20 rounded-xl border border-red-100 dark:border-red-800/50 text-xs text-red-700 dark:text-red-300">
          <XCircle className="w-3.5 h-3.5 shrink-0 mt-0.5" />
          <span>
            <strong>Appointment Rejected.</strong>{" "}
            {apt.notes || "The doctor is not available for this slot. Please book a new appointment."}
          </span>
        </div>
      )}

      {/* AI Checklist (collapsible) */}
      {apt.ai_checklist && apt.ai_checklist.length > 0 && isUpcoming && (
        <div>
          <button
            onClick={() => setShowChecklist(!showChecklist)}
            className="flex items-center gap-1.5 text-xs font-semibold text-emerald-600 dark:text-emerald-400 hover:underline"
          >
            <FileText className="w-3.5 h-3.5" />
            {showChecklist ? "Hide" : "View"} AI Preparation Checklist ({apt.ai_checklist.length} items)
            <ChevronRight className={`w-3.5 h-3.5 transition-transform ${showChecklist ? "rotate-90" : ""}`} />
          </button>
          {showChecklist && (
            <div className="mt-2 p-3.5 bg-emerald-50 dark:bg-emerald-900/20 rounded-xl border border-emerald-100 dark:border-emerald-800/50 space-y-2">
              {apt.ai_checklist.map((item: string, idx: number) => (
                <div key={idx} className="flex items-start gap-2 text-xs text-emerald-800 dark:text-emerald-300">
                  <CheckCircle2 className="w-3.5 h-3.5 shrink-0 mt-0.5 text-emerald-500" />
                  <span>{item}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Actions */}
      <div className="flex items-center gap-2 flex-wrap pt-1 border-t border-slate-100 dark:border-slate-800">
        <button
          onClick={handleDownloadSlip}
          className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-slate-600 dark:text-slate-300 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 rounded-lg transition-colors"
        >
          <Download className="w-3.5 h-3.5" />
          Download Slip
        </button>

        {isUpcoming && (
          <>
            <Link
              href="/patient/appointments/book"
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/20 hover:bg-blue-100 dark:hover:bg-blue-900/40 rounded-lg transition-colors"
            >
              <RotateCcw className="w-3.5 h-3.5" />
              Book New Slot
            </Link>

            {(apt.status === "pending" || apt.status === "confirmed") && (
              <button
                onClick={() => onCancel(apt.id)}
                disabled={cancelling}
                className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-red-600 dark:text-red-400 bg-red-50 dark:bg-red-900/20 hover:bg-red-100 dark:hover:bg-red-900/40 rounded-lg transition-colors disabled:opacity-50"
              >
                {cancelling ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Ban className="w-3.5 h-3.5" />}
                Cancel Appointment
              </button>
            )}
          </>
        )}

        {apt.status === "rejected" && (
          <Link
            href="/patient/appointments/book"
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-emerald-600 dark:text-emerald-400 bg-emerald-50 dark:bg-emerald-900/20 hover:bg-emerald-100 rounded-lg transition-colors"
          >
            <Plus className="w-3.5 h-3.5" />
            Book New Appointment
          </Link>
        )}
      </div>
    </div>
  );
}

type TabKey = "upcoming" | "pending" | "completed" | "cancelled";

export default function AppointmentsPage() {
  const { userProfile } = useAuth();
  const [appointments, setAppointments] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [activeTab, setActiveTab] = useState<TabKey>("upcoming");
  const [cancellingId, setCancellingId] = useState<string | null>(null);
  const pollingRef = useRef<NodeJS.Timeout | null>(null);

  const patientId = userProfile?.patient_profile?.patient_id || userProfile?.id || "";

  const fetchAppointments = useCallback(async (silent = false) => {
    if (!patientId) return;
    if (!silent) setLoading(true);
    setError("");
    try {
      const data = await appointmentService.getPatientAppointments(patientId);
      setAppointments(Array.isArray(data) ? data : []);
    } catch (err: any) {
      if (!silent) setError(err.message || "Failed to load appointments");
    } finally {
      if (!silent) setLoading(false);
    }
  }, [patientId]);

  // Initial load
  useEffect(() => {
    fetchAppointments(false);
  }, [fetchAppointments]);

  // Polling every 30s for real-time updates
  useEffect(() => {
    pollingRef.current = setInterval(() => {
      fetchAppointments(true);
    }, 30000);
    return () => {
      if (pollingRef.current) clearInterval(pollingRef.current);
    };
  }, [fetchAppointments]);

  const handleCancel = async (appointmentId: string) => {
    setCancellingId(appointmentId);
    try {
      await appointmentService.cancelAppointment(appointmentId);
      await fetchAppointments(true);
    } catch (err: any) {
      alert(err.message || "Failed to cancel appointment");
    } finally {
      setCancellingId(null);
    }
  };

  // Tab filters
  const upcomingApts = appointments.filter(a => ["pending", "confirmed", "rescheduled"].includes(a.status));
  const pendingApts = appointments.filter(a => a.status === "pending");
  const completedApts = appointments.filter(a => a.status === "completed");
  const cancelledRejected = appointments.filter(a => ["cancelled", "rejected"].includes(a.status));

  const tabs: { key: TabKey; label: string; count: number; color: string }[] = [
    { key: "upcoming", label: "Upcoming", count: upcomingApts.length, color: "text-emerald-600 dark:text-emerald-400" },
    { key: "pending", label: "Pending", count: pendingApts.length, color: "text-amber-600 dark:text-amber-400" },
    { key: "completed", label: "Completed", count: completedApts.length, color: "text-purple-600 dark:text-purple-400" },
    { key: "cancelled", label: "Cancelled / Rejected", count: cancelledRejected.length, color: "text-slate-500" },
  ];

  const activeList = {
    upcoming: upcomingApts,
    pending: pendingApts,
    completed: completedApts,
    cancelled: cancelledRejected,
  }[activeTab];

  return (
    <ProtectedRoute allowedRole="patient">
      <div className="flex min-h-screen bg-slate-50 dark:bg-slate-950 font-sans text-slate-800 dark:text-slate-100">
        <PatientSidebar />

        <main className="flex-1 p-6 md:p-8 overflow-y-auto max-w-5xl">
          <div className="space-y-6">

            {/* Header */}
            <div className="flex flex-wrap items-center justify-between gap-4">
              <div>
                <h1 className="text-2xl font-bold text-slate-900 dark:text-white tracking-tight">
                  My Appointments
                </h1>
                <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
                  Track, manage and book medical appointments · auto-refreshes every 30s
                </p>
              </div>
              <div className="flex items-center gap-3">
                <button
                  onClick={() => fetchAppointments(false)}
                  disabled={loading}
                  className="flex items-center gap-2 px-3 py-2 text-xs font-semibold rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors shadow-sm disabled:opacity-50"
                >
                  <RefreshCw className={`w-3.5 h-3.5 ${loading ? "animate-spin" : ""}`} />
                  Refresh
                </button>
                <Link
                  href="/patient/appointments/book"
                  className="flex items-center gap-2 px-4 py-2 text-xs font-bold rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white shadow-sm transition-colors"
                >
                  <Plus className="w-3.5 h-3.5" />
                  Book Appointment
                </Link>
              </div>
            </div>

            {/* Error */}
            {error && (
              <div className="p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 text-red-700 dark:text-red-400 rounded-2xl text-sm flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <AlertCircle className="w-4 h-4 shrink-0" />
                  {error}
                </span>
                <button onClick={() => fetchAppointments(false)} className="underline font-semibold text-xs">Retry</button>
              </div>
            )}

            {/* Tabs */}
            <div className="flex gap-1 p-1 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl shadow-sm w-fit">
              {tabs.map(tab => (
                <button
                  key={tab.key}
                  onClick={() => setActiveTab(tab.key)}
                  className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-semibold transition-all ${
                    activeTab === tab.key
                      ? "bg-slate-900 dark:bg-white text-white dark:text-slate-900 shadow"
                      : "text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800"
                  }`}
                >
                  {tab.label}
                  {tab.count > 0 && (
                    <span className={`px-1.5 py-0.5 rounded-full text-[10px] font-bold ${
                      activeTab === tab.key
                        ? "bg-white/20 dark:bg-slate-900/20 text-white dark:text-slate-900"
                        : `bg-slate-100 dark:bg-slate-800 ${tab.color}`
                    }`}>
                      {tab.count}
                    </span>
                  )}
                </button>
              ))}
            </div>

            {/* Content */}
            {loading ? (
              <div className="space-y-4">
                {[1, 2, 3].map(i => <AppointmentSkeleton key={i} />)}
              </div>
            ) : activeList.length === 0 ? (
              <div className="py-20 text-center bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm">
                <div className="w-16 h-16 rounded-2xl bg-emerald-50 dark:bg-emerald-900/20 flex items-center justify-center mx-auto mb-4">
                  <Calendar className="w-8 h-8 text-emerald-400" />
                </div>
                <h3 className="font-bold text-slate-800 dark:text-white mb-2">No appointments here</h3>
                <p className="text-xs text-slate-500 mb-6">
                  {activeTab === "upcoming"
                    ? "You have no upcoming appointments. Book one now!"
                    : `No ${activeTab} appointments found.`}
                </p>
                {activeTab === "upcoming" && (
                  <Link
                    href="/patient/appointments/book"
                    className="inline-flex items-center gap-2 px-5 py-2.5 bg-emerald-600 hover:bg-emerald-700 text-white text-sm font-bold rounded-xl shadow-sm transition-colors"
                  >
                    <Plus className="w-4 h-4" />
                    Book Your First Appointment
                  </Link>
                )}
              </div>
            ) : (
              <div className="space-y-4">
                {activeList.map((apt) => (
                  <AppointmentCard
                    key={apt.id}
                    apt={apt}
                    onCancel={handleCancel}
                    cancelling={cancellingId === apt.id}
                  />
                ))}
              </div>
            )}

          </div>
        </main>
      </div>
    </ProtectedRoute>
  );
}
